name: merged
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        target:
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.target }}
          restore-keys: Library-

      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.target }}
          unityVersion: 2020.3.3f1
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.target }}
          path: build/${{ matrix.target }}